### ISSUE TITLE
should auto-detect text direction per language

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alignment-editor#6]
As @srdee points out, it's easy to forget to click the text direction radio button on the input form. We should try to auto-detect this per language.

**Comment by srdee** [comment]
I actually disagree with implementing autodetection (or at least enforced autodetection) for direction by language--now or in the future, not only on principle, but also because now we have the use-case of Maxim having students write Arabic in Latin script.

I think a better solution would be to just NOT default the radio button to LTR, and make the directionality selection mandatory to hit the 'Align' button, so people have to give it some thought. Unless @balmas @maryam-foradi or @maximromanov disagree, I'll close this issue and enter a new one accordingly.

**Comment by maximromanov** [comment]
I agree.

Best,
Maxim

<http://maximromanov.github.io/files/RM_Business_Card_personal_compact.gif>

**Comment by maryam-foradi** [comment]
I also agree
